// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.1
// source: protoc-gen-go-http/proto/options/openim.proto

package openim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token bool `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_go_http_proto_options_openim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_go_http_proto_options_openim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_protoc_gen_go_http_proto_options_openim_proto_rawDescGZIP(), []int{0}
}

func (x *MethodOptions) GetToken() bool {
	if x != nil {
		return x.Token
	}
	return false
}

type AutoServerOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token bool `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AutoServerOptions) Reset() {
	*x = AutoServerOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_go_http_proto_options_openim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoServerOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoServerOptions) ProtoMessage() {}

func (x *AutoServerOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_go_http_proto_options_openim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoServerOptions.ProtoReflect.Descriptor instead.
func (*AutoServerOptions) Descriptor() ([]byte, []int) {
	return file_protoc_gen_go_http_proto_options_openim_proto_rawDescGZIP(), []int{1}
}

func (x *AutoServerOptions) GetToken() bool {
	if x != nil {
		return x.Token
	}
	return false
}

var file_protoc_gen_go_http_proto_options_openim_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         521191,
		Name:          "openim.method",
		Tag:           "bytes,521191,opt,name=method",
		Filename:      "protoc-gen-go-http/proto/options/openim.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*AutoServerOptions)(nil),
		Field:         521191,
		Name:          "openim.server",
		Tag:           "bytes,521191,opt,name=server",
		Filename:      "protoc-gen-go-http/proto/options/openim.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional openim.MethodOptions method = 521191;
	E_Method = &file_protoc_gen_go_http_proto_options_openim_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional openim.AutoServerOptions server = 521191;
	E_Server = &file_protoc_gen_go_http_proto_options_openim_proto_extTypes[1]
)

var File_protoc_gen_go_http_proto_options_openim_proto protoreflect.FileDescriptor

var file_protoc_gen_go_http_proto_options_openim_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d,
	0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x29, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3a, 0x4f, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe7, 0xe7, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x3a, 0x54, 0x0a, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe7, 0xe7, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x42, 0x23, 0x5a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x67, 0x6f, 0x2d, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x3b, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_gen_go_http_proto_options_openim_proto_rawDescOnce sync.Once
	file_protoc_gen_go_http_proto_options_openim_proto_rawDescData = file_protoc_gen_go_http_proto_options_openim_proto_rawDesc
)

func file_protoc_gen_go_http_proto_options_openim_proto_rawDescGZIP() []byte {
	file_protoc_gen_go_http_proto_options_openim_proto_rawDescOnce.Do(func() {
		file_protoc_gen_go_http_proto_options_openim_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_gen_go_http_proto_options_openim_proto_rawDescData)
	})
	return file_protoc_gen_go_http_proto_options_openim_proto_rawDescData
}

var file_protoc_gen_go_http_proto_options_openim_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoc_gen_go_http_proto_options_openim_proto_goTypes = []interface{}{
	(*MethodOptions)(nil),               // 0: openim.MethodOptions
	(*AutoServerOptions)(nil),           // 1: openim.AutoServerOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
}
var file_protoc_gen_go_http_proto_options_openim_proto_depIdxs = []int32{
	2, // 0: openim.method:extendee -> google.protobuf.MethodOptions
	3, // 1: openim.server:extendee -> google.protobuf.ServiceOptions
	0, // 2: openim.method:type_name -> openim.MethodOptions
	1, // 3: openim.server:type_name -> openim.AutoServerOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_gen_go_http_proto_options_openim_proto_init() }
func file_protoc_gen_go_http_proto_options_openim_proto_init() {
	if File_protoc_gen_go_http_proto_options_openim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_gen_go_http_proto_options_openim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_gen_go_http_proto_options_openim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoServerOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_gen_go_http_proto_options_openim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protoc_gen_go_http_proto_options_openim_proto_goTypes,
		DependencyIndexes: file_protoc_gen_go_http_proto_options_openim_proto_depIdxs,
		MessageInfos:      file_protoc_gen_go_http_proto_options_openim_proto_msgTypes,
		ExtensionInfos:    file_protoc_gen_go_http_proto_options_openim_proto_extTypes,
	}.Build()
	File_protoc_gen_go_http_proto_options_openim_proto = out.File
	file_protoc_gen_go_http_proto_options_openim_proto_rawDesc = nil
	file_protoc_gen_go_http_proto_options_openim_proto_goTypes = nil
	file_protoc_gen_go_http_proto_options_openim_proto_depIdxs = nil
}
